dbt_load_core:
  dag_type: dbt_dag
  dag_conf:
    schedule_interval: null
    description: DAG that parses dbt's manifest.json file and maps the dbt dependencies into airflow tasks.
    tags: [deel_takehome_test]
    default_args:
      start_date: 2024-04-01
    query_params:
      days_to_reload: 4